In [1]:
import pandas as pd
import numpy as np
from scipy.stats import randint

In [11]:
def rantobin(array):            #random number list to binary digits
    for i in range(len(array)):
        if array[i] < 0.5:
            array[i] = 0
        else:
            array[i] = 1
    return array.astype(int)

def slic(array,bits):               #slicing the big array to 4 smaller arrays
    
    array1 = array[:bits]
    array2 = array[bits:2*bits]
    array3 = array[2*bits:3*bits]
    array4 = array[3*bits:4*bits]
    
    return np.array(array1),np.array(array2),np.array(array3),np.array(array4)

def bintonor(array):                      #convert binary array to number
    j = len(array)
    num = 0
    for i in range(j):
        num = num + (2**(j-i-1))*array[i]
    return num

def nortobin(num):                        #convert num to binary array
    temp = format(num, "b")
    array = list(str(temp))
    return np.array(array).astype(int)

def arrtostr(array):
    string = ''.join(map(str,array))
    return string

def obj(x):
    x = x
    return (1.076*(10**(-7))*(x**3) + ((8.76*(10**5))/x))



In [21]:
obj(775)

1180.4086993951612

In [18]:
bintonor([0,0,1,1,0,1,1,0,1,1])

219

In [12]:
#init = rantobin(rano)
#init1,init2,init3,init4 = slic(init,6)

def GA(init_array,bits):
    

    init1,init2,init3,init4 = slic(init_array,bits)
    print("Initial Population")
    print(init1)
    print(init2)
    print(init3)
    print(init4)
    print("\n")
    
    print("D value")
    d1 = bintonor(init1)/prec
    d2 = bintonor(init2)/prec
    d3 = bintonor(init3)/prec
    d4 = bintonor(init4)/prec
    print(bintonor(init1)/prec)
    print(bintonor(init2)/prec)
    print(bintonor(init3)/prec)
    print(bintonor(init4)/prec)
    print("\n")
    
    print("Y = f(D)")    
    y1 = obj(bintonor(init1)/prec)
    y2 = obj(bintonor(init2)/prec)
    y3 = obj(bintonor(init3)/prec)
    y4 = obj(bintonor(init4)/prec)
    print(obj(bintonor(init1)/prec))
    print(obj(bintonor(init2)/prec))
    print(obj(bintonor(init3)/prec))
    print(obj(bintonor(init4)/prec))
    sum = obj(bintonor(init1)/prec) + obj(bintonor(init2)/prec) + obj(bintonor(init3)/prec) + obj(bintonor(init4)/prec)
    print("\n")
    
    print("P-select")
    p1 = y1/sum
    p2 = y2/sum
    p3 = y3/sum
    p4 = y4/sum
    print(y1/sum)
    print(y2/sum)
    print(y3/sum)
    print(y4/sum)
    print("\n")


In [13]:
rano = np.array([0.001213,0.499629,0.108501,0.557434,0.092645,0.762627,0.032722,0.352862,0.941875,0.199044,
        0.339548,0.155062,0.751033,0.634536,0.227241,0.721023,0.789616,0.760869,0.805480,0.585186,
        0.898980,0.282693,0.386183,0.799824,0.589628,0.696237,0.299315,0.574100,0.240002,0.936553,
        0.543258,0.582447,0.239493,0.199621,0.191479,0.222878,0.052303,0.120791,0.826543,0.986111])

prec = 1
bits = 10

In [14]:
# Iteration - 1

#iter_1 = [0,0,0,1,1,1,1,0,0,1,0,0,1,0,1,1,0,1,1,1,1,0,0,0,1,0,1,0,0,1,0,1]
iter_1 = rantobin(rano)[:40]
#len(iter_1)
GA(iter_1,bits)

Initial Population
[0 0 0 1 0 1 0 0 1 0]
[0 0 1 1 0 1 1 1 1 1]
[1 0 0 1 1 1 0 1 0 1]
[1 1 0 0 0 0 0 0 1 1]


D value
82.0
223.0
629.0
771.0


Y = f(D)
10682.986156465091
3929.444358485433
1419.4639455879103
1185.5013580116156


P-select
0.6204763060018186
0.22822524381136916
0.08244359138555539
0.06885485880125695




In [8]:
# Iteration - 2

iter_2 = [0,1,0,0,1,0,0,0,0,1,0,0,1,1,1,0,0,0,0,1,1,0,1,1,0,1,1,1,1,0,1,1]
GA(iter_2,bits)
#len(iter_2)

Initial Population
[0 1 0 0 1 0 0 0]
[0 1 0 0 1 1 1 0]
[0 0 0 1 1 0 1 1]
[0 1 1 1 1 0 1 1]


D value
7.2
7.8
2.7
12.3


Y = f(D)
1798.015802469136
1775.5815121630508
1743.0512620027437
1519.9542844867474


P-select
0.2629984275807614
0.25971693079620134
0.2549586830493123
0.22232595857372492




In [ ]:
# Iteration - 3
